routes/web.php
Route::any('/delete/{id}', 'SubjectsController@destroy')->name('subjectdestroy');
 });
// Section
Route::prefix('sections')->group(function(){
Route::get('/', 'SectionsController@index')->name('sections');
Route::post('/', 'SectionsController@store')->name('sectionssave');
Route::post('/{id}', 'SectionsController@update')->name('sectionsupdate');
Route::any('/delete/{id}', 'SectionsController@destroy')->name('sectionsdestroy');
});
//lesson
Route::prefix('lessons')->group(function(){
Route::get('/', 'LessonsController@index')->name('lesson');
Route::post('/', 'LessonsController@store')->name('lessonsave');
Route::match(['get', 'post'],'/edit/{id}', 'LessonsController@edit')->name('lessonedit');
Route::post('/update/{id}','LessonsController@update')->name('lessonupdate');
Route::any('/delete/{id}', 'LessonsController@destroy')->name('lessondestroy');
 });
//Create
Route::prefix('exam')->group(function(){
Route::get('/create/', 'CreateExamsController@index')->name('create');
Route::post('/create/', 'CreateExamsController@store')->name('createsave');
Route::post('/create/update/{id}','CreateExamsController@update')->name('createupdate');
Route::any('/create/delete/{id}', 'CreateExamsController@destroy')->name('createdelete');
});
//Exam
Route::prefix('exam/schedule')->group(function(){
Route::get('/', 'ExamsController@index')->name('exam');
Route::post('/', 'ExamsController@store')->name('examsave');
Route::match(['get', 'post'],'/edit/{id}', 'ExamsController@edit')->name('examedit');
Route::post('/update/{id}','ExamsController@update')->name('examupdate');
Route::any('/delete/{id}', 'ExamsController@destroy')->name('examdelete');
Route::match(['get', 'post'], '/view','ExamsController@viewexam')->name('viewexam');
Route::match(['get', 'post'], '/view/individual','ExamsController@individual')->name('individual');
Route::post('/get-selected-date', 'ExamsController@getSelectedDate');
Route::post('/get-selected-subject', 'ExamsController@getSelectedSubject');
 });
//Mark
Route::prefix('mark')->group(function(){
Route::get('/add/', 'MarksController@markadd')->name('markadd');
Route::get('/view/', 'MarksController@markview')->name('markview');
Route::match(['get', 'post'],'/subject/add', 'MarksController@subjectmarkadd')->name('subjectmarkadd');
Route::match(['get', 'post'],'/subject/add1', 'MarksController@subjectmarksave')->name('subjectmarksave');
Route::match(['get','post'],'/view/all/', 'MarksController@classmarkview')->name('classmarkview');
Route::post('/schedule/get-selected-subject', 'ExamsController@getSelectedSubject');

 });
//search academic year and clss
    Route::post('/search/mark',function(){
    $academic_year = Input::get ('academic_year');
    $cname = Input::get ('cname');
    $student = StudentAdmission::where('cname',$cname)->where('academic_year', $academic_year)->get();
    if(count($student) >0)
        return view('classmarkview')->withDetails($student)->withQuery($q);
        
    else return view('classmarkview')->withMessage('Sorry. wrong input!');
});
//Students
Route::match(['get', 'post'], '/students', 'StudentsController@index')->name('studentcategory');
Route::get('/student/admission', 'StudentsController@admission')->name('studentadmission');
Route::resource('/studentlists', 'StudentListsController');
Route::resource('/studentadmissions', 'StudentAdmissionsController');
//Guardians
Route::resource('/guardians', 'GuardiansController');
//Events
Route::resource('/events', 'EventsController');
Route::post('/eventtypes/{id}/edit', 'EventTypesController@editEvent')->name('eventtypes.edit');
Route::resource('/eventtypes', 'EventTypesController');
Route::match(['get', 'post'],'/event/add', 'EventsController@index')->name('add.event');
Route::get('/event/store', 'EventsController@store')->name('event.store');
Route::post('/event/store', 'EventsController@store')->name('event.store');
Route::match(['get', 'post'],'/event/edit/{id}', 'EventsController@editEvent')->name('edit.event');
Route::any('/event/update/{id}', 'EventsController@update')->name('updateevent');
//studentcategory
Route::post('/studentcategories/{id}/edit', 'StudentcategoriesController@edit')->name('studentcategories.edit');
Route::resource('/studentcategories', 'StudentcategoriesController');
//Route::get('/studentcategories/delete/{id}', 'StudentcategoriesController@destroy')->name('delete.studentcategories');
//studentadmission
Route::resource('/studentadmissions', 'StudentAdmissionsController');
Route::resource('/guardians', 'GuardiansController');
Route::get('/student/create','StudentAdmissionsController@guardian_index')->name('guardian_index');
Route::get('/student/idcard','StudentAdmissionsController@idcard_index')->name('idcard_index');
Route::match(['get','post'],'/guardians/edit/{id}', 'StudentAdmissionsController@editGuardian')->name('guardians.edit');
Route::any('/guardians/update', 'StudentAdmissionsController@update')->name('updateguardian');
//Finances
 Route::resource('/finances', 'FinancesController');
 //Route::resource('/feecategory', 'FeecategoryController');
//rollnumber
Route::resource('/rollnumbers', 'RollnumbersController');
 //Finances
 Route::resource('/finances', 'FinancesController');
 //Route::resource('/feecategory', 'FeecategoryController');
 Route::get('/feecategory', 'FeecategoryController@index')->name('feecategory.index');
 Route::post('/feecategory/store', 'FeecategoryController@store')->name('feecategory.store');
 Route::get('/feecategory/{id}', 'FeecategoryController@edit')->name('feecategory.edit');
 Route::post('/feecategory/update/{id}', 'FeecategoryController@update')->name('feecategory.update');
 Route::get('/feecategory/destroy/{id}', 'FeecategoryController@destroy')->name('feecategory.destroy');
 //Route::resource('/feesubcategory', 'FeesubcategoryController');
 Route::get('/feesubcategory', 'FeesubcategoryController@index')->name('feesubcategory.index');
 Route::post('/feesubcategory/store', 'FeesubcategoryController@store')->name('feesubcategory.store');
 Route::get('/feesubcategory/{id}', 'FeesubcategoryController@edit')->name('feesubcategory.edit');
 Route::post('/feesubcategory/update/{id}', 'FeesubcategoryController@update')->name('feesubcategory.update');
 Route::get('/feesubcategory/destroy/{id}', 'FeesubcategoryController@destroy')->name('feesubcategory.destroy');
 //Route::resource('/feesubcategoryfine', 'FeesubcategoryfineController');
 Route::get('/feesubcategoryfine', 'FeesubcategoryfineController@index')->name('feesubcategoryfine.index');
 Route::post('/feesubcategoryfine/store', 'FeesubcategoryfineController@store')->name('feesubcategoryfine.store');
 Route::get('/feesubcategoryfine/{id}', 'FeesubcategoryfineController@edit')->name('feesubcategoryfine.edit');
 Route::post('/feesubcategoryfine/update/{id}', 'FeesubcategoryfineController@update')->name('feesubcategoryfine.update');
 Route::get('/feesubcategoryfine/destroy/{id}', 'FeesubcategoryfineController@destroy')->name('feesubcategoryfine.destroy');
 //Route::FEEWAIVER
 Route::get('/feewaiver', 'FeewaiverController@index')->name('feewaiver.index');
 Route::post('/feewaiver/store', 'FeewaiverController@store')->name('feewaiver.store');
 Route::get('/feewaiver/{id}', 'FeewaiverController@edit')->name('feewaiver.edit');
 Route::post('/feewaiver/update/{id}', 'FeewaiverController@update')->name('feewaiver.update');
 Route::get('/feewaiver/destroy/{id}', 'FeewaiverController@destroy')->name('feewaiver.destroy');
//ROUTE::FEE ALLOCATION
 Route::get('/feeallocate', 'FeeallocateController@index')->name('feeallocate.index');
 Route::post('/feeallocate/store', 'FeeallocateController@store')->name('feeallocate.store');
 Route::get('/feeallocate/{id}', 'FeeallocateController@edit')->name('feeallocate.edit');
 Route::post('/feeallocate/update/{id}', 'FeeallocateController@update')->name('feeallocate.update');
 Route::get('/feeallocate/destroy/{id}', 'FeeallocateController@destroy')->name('feeallocate.destroy');
//ROUTE::FEE COLLECTION
 Route::get('/feecollection', 'FeecollectionController@index')->name('feecollection.index');
 Route::post('/feecollection/store', 'FeecollectionController@store')->name('feecollection.store');
 Route::get('/feecollection/{id}', 'FeecollectionController@edit')->name('feecollection.edit');
 Route::post('/feecollection/update/{id}', 'FeecollectionController@update')->name('feecollection.update');
 Route::get('/feecollection/destroy/{id}', 'FeecollectionController@destroy')->name('feecollection.destroy');
//ROURTE:: FEE TYPE
Route::get('/feetype', 'FeetypeController@index')->name('feetype.index');
Route::post('/feetype/store', 'FeetypeController@store')->name('feetype.store');
Route::post('/feetype/{id}', 'FeetypeController@edit')->name('feetype.edit');
Route::post('/feetype/update/{id}', 'FeetypeController@update')->name('feetype.update');
Route::delete('/feetype/destroy/{id}', 'FeetypeController@destroy')->name('feetype.destroy');
Route::get('/feetype/destroy/{id}', 'FeetypeController@destroy')->name('feetype.destroy');
//ROUTE::INVOICE
//search
    Route::post('/search',function(){
    $q = Input::get ('q');
    $y = Input::get ('y');
    $c = Input::get ('c');
    //if($q!=="") {
    //$student = StudentAdmission::where('rollno','LIKE',$q)->orWhere('academic_year','LIKE',$q)->get();
    $student = StudentAdmission::where('rollno',$q)->where('academic_year', $y)->where('room_id', $c)->get();
    if(count($student) >0)
    {
        return view('welcome')->withDetails($student)->withQuery($q);
    }
                
    else return view('welcome')->withMessage('Sorry. wrong input!');
});

//ROUTE::INVOICE
Route::get('/invoice', 'InvoiceController@index')->name('invoice.index');
Route::post('/invoice/store', 'InvoiceController@store')->name('invoice.store');
Route::get('/invoice/edit/{id}', 'InvoiceController@edit')->name('invoice.edit');
Route::get('/invoice/editinvoice/{id}', 'InvoiceController@editinvoice')->name('invoice.editinvoice');

app/Guardian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guardian extends Model
{
    public function student()
    {
    	return $this->belongsToMany('App\Student');
    }
}

app/Http/Controllers/GuardiansController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\StudentAdmission;
use App\Guardian;
use Session;

class GuardiansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['admission'] = StudentAdmission::all();
        return view ('backend.guardians.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(StudentAdmission $admission)
    {
        $arr['studentadmission']= StudentAdmission::all();
        return view('backend.guardians.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, StudentAdmission $admission)
    {

        $admission->pname = $request->pname;
        $admission->relation = $request->relation;
        $admission->education = $request->education;
        $admission->occupation = $request->occupation;
        $admission->income = $request->income;
        $admission->address = $request->address;
        $admission->pcity = $request->pcity;
        $admission->pcountry = $request->pcountry;
        $admission->pprovince = $request->pprovince;
        $admission->pphone = $request->pphone;
        $admission->pmobile = $request->mobile;
        $admission->pemail = $request->pemail;       
        $admission->save();
        Session::flash('success', 'guardian Successfully Created');

        return redirect()->route('guardians.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }
}

resources/views/backend/guardians/edit.blade.php
@extends('backend.includes.app')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row page-titles">
                    <div class="col-md-10 align-self-center">
                        <h4 class="text-themecolor">Guardian List</h4>
                    </div>
                    <div class="col-md-10 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item">Guardian</li>
                                <li class="breadcrumb-item active">List</li>
                            </ol>
                            
                        </div>
                    </div>
                </div><!-- /.row -->
   <!-- /.container-fluid -->
<div class="content">

<form enctype="multipart/form-data" method="POST" action="{{route('updateguardian',['id' => $studentadmission->id])}}">
<input type="hidden" name="_token" value="{{csrf_token()}}">
@method('PUT')
                        <p><b>GUARDIAN'S DETAILS</b></p>  
                    <hr>
                        <div class="row">
                            
                            <div class="form-group col-sm-4">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="pname" value="{{$studentadmission->pname}}">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="relation">Relation</label>
                                <input type="text" class="form-control" name="relation" value="{{$studentadmission->relation}}">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="occupation">Occupation</label>
                                <input type="text" class="form-control" name="occupation" value="{{$studentadmission->occupation}}">
                              </div>

                               <div class="form-group col-sm-4">
                                <label for="education">Education</label>
                                <input type="text" class="form-control" name="education" value="{{$studentadmission->education}}">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="income">Income</label>
                                <input type="text" class="form-control" name="income" value="{{$studentadmission->inome}}">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="address">Address</label>
                                <input type="text" class="form-control" name="address" value="{{$studentadmission->address}}">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pcity">City</label>
                                <input type="text" class="form-control" name="pcity">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pcountry">Country</label>
                                <input type="text" class="form-control" name="pcountry">
                              </div>
                

                              <div class="form-group col-sm-4">
                                <label for="mobile">Mobile</label>
                                <input type="text" class="form-control" name="mobile">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="phone">Phone</label>
                                <input type="text" class="form-control" name="phone">
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="email">email</label>
                                <input type="text" class="form-control" name="email">
                              </div>

                                  <input type="hidden" class="form-control" name="academic_year" value="{{$studentadmission->academic_year}}"> 

                                  
                                  <input type="hidden" class="form-control" name="register_number" value="{{$studentadmission->register_number}}"> 
                                  <input type="hidden" class="form-control" name="joining_date" value="{{$studentadmission->joining_date}}" > 

                                  <input type="hidden" class="form-control" name="course" value="{{$studentadmission->course}}"> 
                        
                        
                                  <input type="hidden" class="form-control" name="batch"  value="{{$studentadmission->batch}}"> 
                              

                                  <input type="hidden" class="form-control" name="rollno"  value="{{$studentadmission->rollno}}"> 

                                  <input type="hidden" class="form-control" name="first_name"  value="{{$studentadmission->first_name}}"> 

                              
                                  <input type="hidden" class="form-control" name="middle_name"  value="{{$studentadmission->middle_name}}"> 
                              

                           
                                  <input type="hidden" class="form-control" name="last_name" value="{{$studentadmission->last_name}}"> 
                              
                                  <input type="hidden" class="form-control" name="dob" value="{{$studentadmission->dob}}"> 
                              
                                  <input type="hidden" class="form-control" name="gender" value="{{$studentadmission->gender}}">

                                  <input type="hidden" class="form-control" name="blood_group" value="{{$studentadmission->blood_group}}">

                                  <input type="hidden" class="form-control" name="birth_place" value="{{$studentadmission->birth_place}}">

                                  <input type="hidden" class="form-control" name="nationality" value="{{$studentadmission->nationality}}">

                                  <input type="hidden" class="form-control" name="mother_tongue" value="{{$studentadmission->mother_tongue}}">
                                  <input type="hidden" class="form-control" name="category" value="{{$studentadmission->category}}">

                                  <input type="hidden" class="form-control" name="religion" value="{{$studentadmission->religion}}">
                                  <input type="hidden" class="form-control" name="present_address" value="{{$studentadmission->present_address}}">

                                  <input type="hidden" class="form-control" name="permanent_address" value="{{$studentadmission->permanent_address}}">

                                  <div class="col-md-12" >
                                    <div class="text-center">
                                      <input type="submit" value="update" class="btn btn-info btn-xs">
                                    </div>
                                  </div>

                            </div>
                            </div>
                        </div>


                        </div>
                     </div>
                </div>
  </form>                           

                                
 @endsection

resources/views/backend/guardians/index.blade.php
@extends('backend.includes.app')
@section('content')

    
             <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Guardian</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item active">View Guardians</li>
                            </ol>
                            <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><a href="{{ route('studentadmissions.index')}}" class="btn btn-info"><i class="fa fa-plus-circle"></i>View Student List</a></button>
                            
                        </div>
            </div>
        </div>

        
                
                 <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Guardian Information</h4>
                                <div class="table-responsive m-t-40">
                                    <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>SN</th>
                                                <th>Name</th>
                                                <th>Child's Name</th>
                                                <th>Email</th>
                                                <th>Mobile Number</th>
                                                <th>Address</th>
                                                <th>Manage</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            

                                           @foreach($admission as $g)
                                            <tr>
                                                <td>{{$loop->index +1}}</td>
                                                <td>{{$g->pname}}</td>
                                                <td>{{ $g->first_name.' '.$g->middle_name.' '.$g->last_name }}</td>
                                                <td>{{$g->pemail}}</td>
                                                <td>{{$g->pmobile}}</td>
                                                <td>{{$g->parent_municipality}}</td>
                                                <td>
                                                    
                                                    <a href="{{route('guardians.edit',  $g->id)}}" class="text-success p-r-10" data-toggle="tooltip" title="Edit"><i class="ti-marker-alt"></i></a>

                                                    <a href="#" class="ti-eye" data-toggle="modal" data-target=".bs-example-modal-lg{{$g->id}}" class="model_img img-responsive" ></a>

                                                    </td>
                                               
                                            </tr>
                                                <div class="modal fade bs-example-modal-lg{{$g->id}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title" id="myLargeModalLabel">Profile Details: {{ $g->pname}}</h4>
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    </div>
                                                    <div class="modal-body">
                                                        
                                                        <div class="row">
                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Full Name</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->pname}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Education</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->education}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Occupation</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->occupation}}</p>
                                                            </div>

                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Income</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->income}}</p>
                                                            </div>

                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Relation</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->relation}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6"> <strong>Country</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->pcountry}}</p>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            
                                                            <div class="col-md-3 col-xs-6"> <strong>Municipality</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->parent_municipality}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6"> <strong>Street</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->parent_street}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6"> <strong>Ward Number</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->parent_ward_number}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Academic Year</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->academic_year}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6"> <strong>Phone Number</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->pphone}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6 b-r"> <strong>Mobile Number</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->pmobile}}</p>
                                                            </div>
                                                            <div class="col-md-3 col-xs-6"> <strong>Email</strong>
                                                                <br>
                                                                <p class="text-muted">{{$g->pemail}}</p>
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <a href="" class="btn btn-info waves-effect">Edit</a>
                                                        <button type="button" class="btn btn-danger waves-effect text-left" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        
                                            @endforeach

                                           
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
        </div>
    </div>
                                  
                                
 @endsection