routes/web.php
<?php
use Illuminate\Support\Facades\Input;
use App\StudentAdmission;
use App\Setting;
use App\Invoice;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/
Route::get('/', function(){
   if(Auth::guest())
   {
     return Redirect::to('login');
   }
   if(Auth::check()){
     return Redirect::to('/dashboard');
   }
});
Auth::routes();
Route::get('/register', function(){
    return Redirect::to('login');
});
Route::get('/userprofile/edit/{id}', 'UserProfileController@edit')->name('userprofile.edit');
Route::any('/userprofile/update/{id}', 'UserProfileController@update')->name('userprofile.update');
//Employee
Route::match(['get', 'post'],'/employee/add', 'EmployeesController@addEmployee')->name('add.employee');
Route::match(['get', 'post'],'/employee/edit/{id}', 'EmployeesController@editEmployee')->name('edit.employee');
Route::get('/employee', 'EmployeesController@viewEmployee')->name('view.employee');
Route::get('/employee/delete/{id}', 'EmployeesController@deleteEmployee')->name('delete.employee');
//Payroll
Route::match(['get','post'], '/employee/payroll/add/{id}', 'PayrollsController@addPayroll')->name('add.payroll');
Route::get('/employee/payroll/{code}', 'PayrollsController@payrollEmployee')->name('payroll.employee');
Route::match(['get', 'post'], '/employee/depatment-payroll/view','PayrollsController@viewDepartmentPayroll')->name('view.department.payroll');
Route::match(['get', 'post'], '/employee/individual-payroll/view','PayrollsController@viewIndividualPayroll')->name('view.individual.payroll');
Route::match(['get', 'post'], '/employee/annual-payroll/view','PayrollsController@viewAnnualPayroll')->name('view.annual.payroll');
Route::match(['get', 'post'], '/employee/payroll/same-as-previous/{id}','PayrollsController@sameAsPreviousPayroll')->name('same.payroll');
//Salary
Route::match(['get','post'], '/employee/salary/add/{code}', 'SalaryController@addSalary')->name('add.salary');
//Departments
Route::get('/department' , 'DepartmentsController@viewDepartment')->name('view.department');
Route::post('/department', 'DepartmentsController@addDepartment')->name('add.department');
Route::get('/department/delete/{id}', 'DepartmentsController@deleteDepartment')->name('delete.department');
Route::get('/department/view/{id}', 'DepartmentsController@viewSelectedDepartment')->name('view.selected.department');
Route::post('/department/edit/{id}', 'DepartmentsController@editHeadDepartment')->name('editHead.department');
//Designation
Route::get('/designation' , 'DesignationsController@viewDesignation')->name('view.designation');
Route::post('/designation', 'DesignationsController@addDesignation')->name('add.designation');
Route::get('/designation/delete/{id}', 'DesignationsController@deleteDesignation')->name('delete.designation');
Route::get('/designation/view/{id}', 'DesignationsController@viewSelectedDesignation')->name('view.selected.designation');
Route::post('/designation/edit/{id}', 'DesignationsController@editDesignation')->name('edit.designation');
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
//Settings
Route::prefix('settings')->group(function(){
Route::get('/', 'SettingsController@index')->name('settings');
Route::post('/', 'SettingsController@update')->name('settingssave');
});
//Academic
Route::prefix('academic')->group(function(){
Route::get('/', 'AcademicsController@index')->name('academic');
 Route::post('/', 'AcademicsController@store')->name('academicsave');
 Route::match(['get','post'],'/{id}', 'AcademicsController@edit')->name('academicedit');
 Route::match(['get','post'],'/edit/{id}', 'AcademicsController@update')->name('academicupdate');
 Route::match(['get','post'],'/{id}', 'AcademicsController@destroy')->name('academicdelete');
});
// class
Route::prefix('classes')->group(function(){
Route::get('/', 'RoomsController@index')->name('classes');
Route::post('/', 'RoomsController@store')->name('classessave');
Route::post('/{id}', 'RoomsController@update')->name('classupdate');
Route::any('/delete/{id}', 'RoomsController@destroy')->name('classdestroy');
});
//Subject
Route::prefix('subjects')->group(function(){
Route::get('/', 'SubjectsController@index')->name('subject');
Route::post('/', 'SubjectsController@store')->name('subjectsave');
Route::match(['get', 'post'],'/edit/{id}', 'SubjectsController@edit')->name('subjectedit');
Route::post('/{id}', 'SubjectsController@update')->name('subjectupdate');
Route::any('/delete/{id}', 'SubjectsController@destroy')->name('subjectdestroy');
 });
// Section
Route::prefix('sections')->group(function(){
Route::get('/', 'SectionsController@index')->name('sections');
Route::post('/', 'SectionsController@store')->name('sectionssave');
Route::post('/{id}', 'SectionsController@update')->name('sectionsupdate');
Route::any('/delete/{id}', 'SectionsController@destroy')->name('sectionsdestroy');
});
//lesson
Route::prefix('lessons')->group(function(){
Route::get('/', 'LessonsController@index')->name('lesson');
Route::post('/', 'LessonsController@store')->name('lessonsave');
Route::match(['get', 'post'],'/edit/{id}', 'LessonsController@edit')->name('lessonedit');
Route::post('/update/{id}','LessonsController@update')->name('lessonupdate');
Route::any('/delete/{id}', 'LessonsController@destroy')->name('lessondestroy');
 });
//Create
Route::prefix('exam')->group(function(){
Route::get('/create/', 'CreateExamsController@index')->name('create');
Route::post('/create/', 'CreateExamsController@store')->name('createsave');
Route::post('/create/update/{id}','CreateExamsController@update')->name('createupdate');
Route::any('/create/delete/{id}', 'CreateExamsController@destroy')->name('createdelete');
});
//Exam
Route::prefix('exam/schedule')->group(function(){
Route::get('/', 'ExamsController@index')->name('exam');
Route::post('/', 'ExamsController@store')->name('examsave');
Route::match(['get', 'post'],'/edit/{id}', 'ExamsController@edit')->name('examedit');
Route::post('/update/{id}','ExamsController@update')->name('examupdate');
Route::any('/delete/{id}', 'ExamsController@destroy')->name('examdelete');
Route::match(['get', 'post'], '/view','ExamsController@viewexam')->name('viewexam');
Route::match(['get', 'post'], '/view/individual','ExamsController@individual')->name('individual');
Route::post('/get-selected-date', 'ExamsController@getSelectedDate');
Route::post('/get-selected-subject', 'ExamsController@getSelectedSubject');
 });
//Mark
Route::prefix('mark')->group(function(){
Route::get('/add/', 'MarksController@markadd')->name('markadd');
Route::get('/view/', 'MarksController@markview')->name('markview');
Route::match(['get', 'post'],'/subject/add', 'MarksController@subjectmarkadd')->name('subjectmarkadd');
Route::match(['get', 'post'],'/subject/add1', 'MarksController@subjectmarksave')->name('subjectmarksave');
Route::match(['get','post'],'/view/all/', 'MarksController@classmarkview')->name('classmarkview');
Route::post('/schedule/get-selected-subject', 'ExamsController@getSelectedSubject');

 });
//search academic year and clss
    Route::post('/search/mark',function(){
    $academic_year = Input::get ('academic_year');
    $cname = Input::get ('cname');
    $student = StudentAdmission::where('cname',$cname)->where('academic_year', $academic_year)->get();
    if(count($student) >0)
        return view('classmarkview')->withDetails($student)->withQuery($q);
        
    else return view('classmarkview')->withMessage('Sorry. wrong input!');
});
//Students
Route::match(['get', 'post'], '/students', 'StudentsController@index')->name('studentcategory');
Route::get('/student/admission', 'StudentsController@admission')->name('studentadmission');
Route::resource('/studentlists', 'StudentListsController');
Route::resource('/studentadmissions', 'StudentAdmissionsController');
//Guardians
Route::resource('/guardians', 'GuardiansController');
//Events
Route::resource('/events', 'EventsController');
Route::post('/eventtypes/{id}/edit', 'EventTypesController@editEvent')->name('eventtypes.edit');
Route::resource('/eventtypes', 'EventTypesController');
Route::match(['get', 'post'],'/event/add', 'EventsController@index')->name('add.event');
Route::get('/event/store', 'EventsController@store')->name('event.store');
Route::post('/event/store', 'EventsController@store')->name('event.store');
Route::match(['get', 'post'],'/event/edit/{id}', 'EventsController@editEvent')->name('edit.event');
Route::any('/event/update/{id}', 'EventsController@update')->name('updateevent');
//studentcategory
Route::post('/studentcategories/{id}/edit', 'StudentcategoriesController@edit')->name('studentcategories.edit');
Route::resource('/studentcategories', 'StudentcategoriesController');
//Route::get('/studentcategories/delete/{id}', 'StudentcategoriesController@destroy')->name('delete.studentcategories');
//studentadmission
Route::resource('/studentadmissions', 'StudentAdmissionsController');
Route::resource('/guardians', 'GuardiansController');
Route::get('/student/create','StudentAdmissionsController@guardian_index')->name('guardian_index');
Route::get('/student/idcard','StudentAdmissionsController@idcard_index')->name('idcard_index');
Route::match(['get','post'],'/guardians/edit/{id}', 'StudentAdmissionsController@editGuardian')->name('guardians.edit');
Route::any('/guardians/update', 'StudentAdmissionsController@update')->name('updateguardian');
//Finances
 Route::resource('/finances', 'FinancesController');
 //Route::resource('/feecategory', 'FeecategoryController');
//rollnumber
Route::resource('/rollnumbers', 'RollnumbersController');
 //Finances

app/StudentAdmission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StudentAdmission extends Model
{

        protected $fillable = ['id', 'first_name', 'middle_name', 'last_name'];

    public function room()
    {
        return $this->belongsTo('App\Room');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function student()
    {
        return $this->belongsTo('App\Student');
    }
    public function invoice()
    {
        return $this->hasMany(StudentAdmission::class);
    }
}

resources/views/backend/studentadmissions/editguardian.blade.php
@extends('backend.includes.app')
@section('content')

 <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Edit parent's Detail</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                                <li class="breadcrumb-item">Parent</li>
                                <li class="breadcrumb-item ">List</li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                            
                        </div>
                    </div>
                </div><!-- /.row -->
   <!-- /.container-fluid -->


<form enctype="multipart/form-data" method="post" action="{{route('studentadmissions.update',$studentadmission->id)}}">
<input type="hidden" name="_token" value="{{csrf_token()}}">
@method('PUT')
                        <p><b>PARENT'S DETAILS</b></p>
                    <hr>
                        <div class="row">
                            <input type="hidden" name="check" value="1">
                            <div class="form-group col-sm-4">
                                <label for="pname">Name</label>
                                <input type="text" class="form-control" name="pname" value="{{$studentadmission->pname}}">
                                  <a href="" style="color:red;">{{ $errors -> first('pname') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="relation">Relation</label>
                                <input type="text" class="form-control" name="relation" value="{{$studentadmission->relation}}">
                                  <a href="" style="color: red;">{{ $errors -> first('relation') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="occupation">Occupation</label>
                                <input type="text" class="form-control" name="occupation" value="{{$studentadmission->occupation}}">
                                  <a href="" style="color: red;">{{ $errors -> first('occupation') }}</a>

                              </div>

                               <div class="form-group col-sm-4">
                                <label for="education">Education</label>
                                <input type="text" class="form-control" name="education" value="{{$studentadmission->education}}">
                                  <a href="" style="color: red;">{{ $errors -> first('education') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="income">Income</label>
                                <input type="text" class="form-control" name="income" value="{{$studentadmission->income}}">
                                  <a href="" style="color: red;">{{ $errors -> first('income') }}</a>

                              </div>
                                
                              <div class="row" >

                              <div class="form-group col-sm-4">
                                <label for="pcountry">Country</label>       
                                <select class="form-control" name="pcountry" id="pcountry ">
                                        @foreach($countries as $country)
                                          <option value="{{ $country->name }}"
                                            @if ($country->name == $studentadmission->pcountry)
                                      selected
                                      @endif >{{ $country->name }}</option>
                                                @endforeach
                                            </select>
                                  <a href="" style="color: red;">{{ $errors -> first('pcountry') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pprovince">Province</label>       
                                <select class="form-control" name="pprovince" id="pprovince ">
                                        @foreach($provinces as $province)
                                          <option value="{{ $province->name }}"
                                            @if ($province->name == $studentadmission->pprovince)
                                      selected
                                      @endif >{{ $province->name }}</option>
                                                @endforeach
                                            </select>
                                  <a href="" style="color: red;">{{ $errors -> first('pprovince') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="parent_municipality">Municipality</label>
                                <input type="text" class="form-control" name="parent_municipality" value="{{$studentadmission->parent_municipality}}">
                                  <a href="" style="color: red;">{{ $errors -> first('parent_municipality') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="parent_street">Street</label>
                                <input type="text" class="form-control" name="parent_street" value="{{$studentadmission->parent_street}}">
                                  <a href="" style="color: red;">{{ $errors -> first('parent_street') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="parent_ward_number">Ward Number </label>
                                <input type="text" class="form-control" name="parent_ward_number" value="{{$studentadmission->parent_ward_number}}">
                                  <a href="" style="color: red;">{{ $errors -> first('parent_ward_number') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pmobile">Mobile</label>
                                <input type="text" class="form-control" name="pmobile" value="{{$studentadmission->pmobile}}">
                                  <a href="" style="color: red;">{{ $errors -> first('pmobile') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pphone">Phone</label>
                                <input type="text" class="form-control" name="pphone" value="{{$studentadmission->pphone}}">
                                  <a href="" style="color: red;">{{ $errors -> first('pphone') }}</a>
                              </div>

                              <div class="form-group col-sm-4">
                                <label for="pemail">email</label>
                                <input type="text" class="form-control" name="pemail" value="{{$studentadmission->pemail}}">
                                  <a href="" style="color: red;">{{ $errors -> first('pemail') }}</a>
                              </div>

                                  <input type="hidden" class="form-control" name="academic_year" value="{{$studentadmission->academic_year}}"> 

                                  <input type="hidden" class="form-control" name="admission_number" value="{{$studentadmission->admission_number}}"> 
                                  
                                  <input type="hidden" class="form-control" name="register_number" value="{{$studentadmission->register_number}}"> 
                                  <input type="hidden" class="form-control" name="joining_date" value="{{$studentadmission->joining_date}}" > 

                                  <input type="hidden" class="form-control" name="room_id" value="{{$studentadmission->room_id}}"> 
                        
                        
                                  <input type="hidden" class="form-control" name="section_id"  value="{{$studentadmission->section_id}}"> 
                              

                                  <input type="hidden" class="form-control" name="rollno"  value="{{$studentadmission->rollno}}"> 

                                  <input type="hidden" class="form-control" name="first_name"  value="{{$studentadmission->first_name}}"> 

                              
                                  <input type="hidden" class="form-control" name="middle_name"  value="{{$studentadmission->middle_name}}"> 
    
                                  <input type="hidden" class="form-control" name="last_name" value="{{$studentadmission->last_name}}"> 
                              
                                  <input type="hidden" class="form-control" name="dob" value="{{$studentadmission->dob}}"> 
                              
                                  <input type="hidden" class="form-control" name="gender" value="{{$studentadmission->gender}}">

                                  <input type="hidden" class="form-control" name="blood_group" value="{{$studentadmission->blood_group}}">

                                  <input type="hidden" class="form-control" name="birth_place" value="{{$studentadmission->birth_place}}">

                                  <input type="hidden" class="form-control" name="nationality" value="{{$studentadmission->nationality}}">

                                  <input type="hidden" class="form-control" name="mother_tongue" value="{{$studentadmission->mother_tongue}}">
                                  <input type="hidden" class="form-control" name="student_id" value="{{$studentadmission->student_id}}">

                                  <input type="hidden" class="form-control" name="religion" value="{{$studentadmission->religion}}">
                                  
                                  <input type="hidden" class="form-control" name="province" value="{{$studentadmission->province}}">
                                  <input type="hidden" class="form-control" name="country" value="{{$studentadmission->country}}">

                                  <input type="hidden" class="form-control" name="permanent_municipality" value="{{$studentadmission->permanent_municipality}}">
                                  
                                  <input type="hidden" class="form-control" name="permanent_street" value="{{$studentadmission->permanent_street}}">
                                  
                                  <input type="hidden" class="form-control" name="permanent_ward_number" value="{{$studentadmission->permanent_ward_number}}">

                                  <input type="hidden" class="form-control" name="temporary_ward_number" value="{{$studentadmission->temporary_ward_number}}">

                                  <input type="hidden" class="form-control" name="temporary_street" value="{{$studentadmission->temporary_street}}">

                                  <input type="hidden" class="form-control" name="temporary_municipality" value="{{$studentadmission->temporary_municipality}}">

                                  <input type="hidden" class="form-control" name="temporary_country" value="{{$studentadmission->temporary_country}}">

                                  <input type="hidden" class="form-control" name="temporary_province" value="{{$studentadmission->temporary_province}}">


                                  <input type="hidden" class="form-control" name="phone_no" value="{{$studentadmission->phone_no}}">
                                  <input type="hidden" class="form-control" name="mobile_no" value="{{$studentadmission->mobile_no}}">
                                  <input type="hidden" class="form-control" name="email" value="{{$studentadmission->email}}">

                                  <div class="col-md-12" >
                                    <div class="text-center">
                                      <button type="submit" class="btn btn-info"> <i class="fa fa-check"></i> Update</button>
                                    </div>
                                  </div>

                            </div>
                            </div>
                        </div>


                        </div>
                     </div>
                </div>
  </form>                           

                                
 @endsection

resources/views/backend/studentadmissions/idcard.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


<div class="id-card-tag"></div>
	<div class="id-card-tag-strip"></div>
	<div class="id-card-hook"></div>
	<div class="id-card-holder">
		<div class="id-card">
			<div class="header">
				<img src="https://lh3.googleusercontent.com/-ebxWAGWvWg0/WTABBfdBv2I/AAAAAAAAAqw/qef78bVeIngorIsmAUD4tWVUd8WDvZyuQCEw/w140-h74-p/Untitled-2.png">
			</div>
			<div class="photo">
				<img src="https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAuXAAAAJDE2YjQzOGZkLTU5YzAtNGRkNC04NTUzLTM3Zjg0ZWVlMGQxZA.jpg">
			</div>
			<h2>{{$studentadmission->first_name}}</h2>
			<div class="qr-code">
				<img src="https://www.shopify.com/growth-tools-assets/qr-code/shopify-faae7065b7b351d28495b345ed76096c03de28bac346deb1e85db632862fd0e4.png">
			</div>
			<h3>www.onetikk.info</h3>
			<hr>
			<p><strong>"PENGG"</strong>HOUSE,4th Floor, TC 11/729(4), Division Office Road <p>
			<p>Near PMG Junction, Thiruvananthapuram Kerala, India <strong>695033</strong></p>
			<p>Ph: 9446062493 | E-ail: info@onetikk.info</p>

		</div>
	</div>
	</body>
<style type="text/css">
	body {
			background-color: #d7d6d3;
			font-family:'verdana';
		}
		.id-card-holder {
			width: 225px;
		    padding: 4px;
		    margin: 0 auto;
		    background-color: #1f1f1f;
		    border-radius: 5px;
		    position: relative;
		}
		.id-card-holder:after {
		    content: '';
		    width: 7px;
		    display: block;
		    background-color: #0a0a0a;
		    height: 100px;
		    position: absolute;
		    top: 105px;
		    border-radius: 0 5px 5px 0;
		}
		.id-card-holder:before {
		    content: '';
		    width: 7px;
		    display: block;
		    background-color: #0a0a0a;
		    height: 100px;
		    position: absolute;
		    top: 105px;
		    left: 222px;
		    border-radius: 5px 0 0 5px;
		}
		.id-card {
			
			background-color: #fff;
			padding: 10px;
			border-radius: 10px;
			text-align: center;
			box-shadow: 0 0 1.5px 0px #b9b9b9;
		}
		.id-card img {
			margin: 0 auto;
		}
		.header img {
			width: 100px;
    		margin-top: 15px;
		}
		.photo img {
			width: 80px;
    		margin-top: 15px;
		}
		h2 {
			font-size: 15px;
			margin: 5px 0;
		}
		h3 {
			font-size: 12px;
			margin: 2.5px 0;
			font-weight: 300;
		}
		.qr-code img {
			width: 50px;
		}
		p {
			font-size: 5px;
			margin: 2px;
		}
		.id-card-hook {
			background-color: #000;
		    width: 70px;
		    margin: 0 auto;
		    height: 15px;
		    border-radius: 5px 5px 0 0;
		}
		.id-card-hook:after {
			content: '';
		    background-color: #d7d6d3;
		    width: 47px;
		    height: 6px;
		    display: block;
		    margin: 0px auto;
		    position: relative;
		    top: 6px;
		    border-radius: 4px;
		}
		.id-card-tag-strip {
			width: 45px;
		    height: 40px;
		    background-color: #0950ef;
		    margin: 0 auto;
		    border-radius: 5px;
		    position: relative;
		    top: 9px;
		    z-index: 1;
		    border: 1px solid #0041ad;
		}
		.id-card-tag-strip:after {
			content: '';
		    display: block;
		    width: 100%;
		    height: 1px;
		    background-color: #c1c1c1;
		    position: relative;
		    top: 10px;
		}
		.id-card-tag {
			width: 0;
			height: 0;
			border-left: 100px solid transparent;
			border-right: 100px solid transparent;
			border-top: 100px solid #0958db;
			margin: -10px auto -30px auto;
		}
		.id-card-tag:after {
			content: '';
		    display: block;
		    width: 0;
		    height: 0;
		    border-left: 50px solid transparent;
		    border-right: 50px solid transparent;
		    border-top: 100px solid #d7d6d3;
		    margin: -10px auto -30px auto;
		    position: relative;
		    top: -130px;
		    left: -50px;
		}
	</style>
		</html>